AllCops:
  TargetRubyVersion: 2.4

Layout/LineLength:
  AllowURI: true
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/MethodLength:
  CountComments: false
  Max: 15

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
